apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: cluster-lifecycle-simulation
  namespace: workflows
spec:
  serviceAccountName: workflow
  entrypoint: cluster-lifecycle
  templates:
    - name: cluster-lifecycle
      steps:
        - - name: check-subnets-available
            template: echo-step
            arguments:
              parameters:
                - name: message
                  value: "Check there are IPs in subnets to migrate cluster blue/green"

          - name: check-others-steps
            template: echo-step
            arguments:
              parameters:
                - name: message
                  value: "Check others steps"

        - - name: step3-provision-tests
            template: echo-step
            arguments:
              parameters:
                - name: message
                  value: "4. Faço o provisionamento do Cluster de Tests"
        - - name: http-request-example
            template: http-request-template
        # Etapa 5: Espera e Staging
        - - name: step4-wait-and-staging
            template: echo-step
            arguments:
              parameters:
                - name: message
                  value: "5. Status Active (7 dias) -> inicio automacao para o ambiente Staging.
                    Gero NameIDs e provisiono Staging."

        # Etapa 5.4: Espera e Sandbox
        - - name: step5-wait-and-sandbox
            template: echo-step
            arguments:
              parameters:
                - name: message
                  value: "5.4 Status Active Staging (7 dias) -> inicio automacao para o ambiente
                    Sandbox."

        # Etapa 6: Drain do Cluster Antigo
        - - name: step6-drain-old-cluster
            template: echo-step
            arguments:
              parameters:
                - name: message
                  value: "6. Habilito o cluster antigo como Draining, para não receber mais
                    aplicações"

        # Etapa 7: Migração de Aplicações
        - - name: step7-migrate-applications
            template: echo-step
            arguments:
              parameters:
                - name: message
                  value: "7. Migro as aplicações do cluster antigo para o novo"

        # Etapa 8: Remoção
        - - name: step8-remove-old-cluster
            template: echo-step
            arguments:
              parameters:
                - name: message
                  value: "8. Após migrar todas as aplicações, inicio o processo de remoção do
                    cluster antigo"

    - name: echo-step
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:latest
        command: [ sh, -c ]
        args: [ "echo '{{inputs.parameters.message}}'" ]

    - name: http-request-template
      container:
        image: curlimages/curl
        command: [ "sh", "-c" ]
        args: [ "curl -s -v --noproxy '*' http://172.18.0.1:8080/workflows" ]
